version: "3"
services:
  web:
    image: wilsonzhong/minimalblog-vue:latest
    container_name: blog_vue
    ports:
      - 80:80
    volumes:
      - ~/mysql:/var/lib/mysql
  database:
    image: mysql:latest
    container_name: blog_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      -e MYSQL_DATABASE=blogdb
      -e MYSQL_USER=blogdb
  server:
    image: wilsonzhong/minimal_blog_server:mysql
    container_name: blog_server
    depends_on:
      - database
    ports:
      - 8081:8081
